### ISSUE TITLE
Bitstamp trading doesnt make real API requests

### ISSUE THREAD

**Issue by vithonch** [DeviaVir/zenbot#1495] opened 2018-03-13 07:25 UTC
`docker-compose exec server zenbot trade bitstamp.ETH-USD --period=5m`

output:
https://gist.github.com/webdevua/b914d2ad2706cb2f81ac002d032773b6      `

Config is correct, but there no real sell buy API calls had happened, any ideas how to fix?

**Comment by DeviaVir** [comment] 2018-03-13 07:39
Duplicate of https://github.com/DeviaVir/zenbot/issues/1288

**Closed as completed by DeviaVir** 2018-03-13 07:39 UTC
Labels: duplicate
