### ISSUE TITLE
Bittrex backfill

### ISSUE THREAD

**Issue by kazdimenator** [DeviaVir/zenbot#816] opened 2017-12-07 22:53 UTC
Bittrex api does not support backfilling (trade/paper only).

Can not I use it?
https://bittrex.com/Api/v2.0/
( https://bittrex.com/Api/v2.0/pub/market/GetTicks?marketName=BTC-LTC&tickInterval=thirtyMin )

or

https://github.com/miti0/python-bittrex

**Comment by DeviaVir** [comment] 2017-12-08 10:55
Pretty sure this has already been asked, so marking duplicate.

**Comment by DeviaVir** [comment] 2017-12-08 14:54
Duplicate of https://github.com/carlos8f/zenbot/issues/499

**Closed as completed by DeviaVir** 2017-12-08 14:54 UTC
Labels: duplicate, enhancement
