### ISSUE TITLE
Zenbot terminated and there is an exception in log

### ISSUE THREAD

**Issue by rgf2004** [DeviaVir/zenbot#462] opened 2017-08-10 08:10 UTC
While running zenbot, it sometimes terminates with the following exception

2017-08-10 07:51:56  299.900 USDT-ETH   +0.3%        5              0.0000   0.1000           0.05 USDT  0.01569 ETH   +31.6%  +29.8%undefined
undefined
undefined
undefined
undefined
2017-08-10 07:57:10  300.000 USDT-ETH   +0.3%       92              0.0000   0.1000           0.05 USDT  0.01569 ETH   +31.6%  +29.8%undefined
/home/pi/tradingBots/zenbot/node_modules/numbro/numbro.js:1111
        var parts = x.toString().split('.');
                     ^

TypeError: Cannot read property 'toString' of undefined
    at multiplier (/home/pi/tradingBots/zenbot/node_modules/numbro/numbro.js:1111:22)
    at /home/pi/tradingBots/zenbot/node_modules/numbro/numbro.js:1127:22
    at Array.reduce (native)
    at correctionFactor (/home/pi/tradingBots/zenbot/node_modules/numbro/numbro.js:1125:21)
    at Object.add (/home/pi/tradingBots/zenbot/node_modules/numbro/numbro.js:1197:47)
    at /home/pi/tradingBots/zenbot/commands/trade.js:234:78
    at /home/pi/tradingBots/zenbot/lib/engine.js:191:14
    at /home/pi/tradingBots/zenbot/extensions/exchanges/bittrex/exchange.js:113:18
    at Request._callback (/home/pi/tradingBots/zenbot/node_modules/node.bittrex.api/node.bittrex.api.js:112:25)
    at self.callback (/home/pi/tradingBots/zenbot/node_modules/request/request.js:188:22)
    at emitOne (events.js:96:13)
    at Request.emit (events.js:188:7)
    at Request.onRequestError (/home/pi/tradingBots/zenbot/node_modules/request/request.js:884:8)
    at emitOne (events.js:96:13)
    at ClientRequest.emit (events.js:188:7)
    at TLSSocket.socketErrorListener (_http_client.js:309:9)
    at emitOne (events.js:96:13)
    at TLSSocket.emit (events.js:188:7)
    at emitErrorNT (net.js:1277:8)
    at _combinedTickCallback (internal/process/next_tick.js:80:11)
    at process._tickCallback (internal/process/next_tick.js:104:9)

**Comment by DeviaVir** [comment] 2017-08-10 08:51
duplicate of https://github.com/carlos8f/zenbot/issues/457

**Closed as completed by DeviaVir** 2017-08-10 08:51 UTC
