### ISSUE TITLE
Different Bittrex error

### ISSUE THREAD

**Issue by brucetus** [DeviaVir/zenbot#659] opened 2017-10-26 19:12 UTC
I already used the fix in #457 and it worked for a couple days. However, I got a new error that occured after selling. 

```
/home/b/zenbot/extensions/exchanges/bittrex/exchange.js:85
        Object.keys(data.result).forEach(function (i) {
               ^

TypeError: Cannot convert undefined or null to object
    at Function.keys (<anonymous>)
    at /home/b/zenbot/extensions/exchanges/bittrex/exchange.js:85:16
    at Request._callback (/home/b/zenbot/node_modules/node.bittrex.api/node.bittrex.api.js:114:25)
    at Request.self.callback (/home/b/zenbot/node_modules/request/request.js:188:22)
    at emitTwo (events.js:125:13)
    at Request.emit (events.js:213:7)
    at Request.<anonymous> (/home/b/zenbot/node_modules/request/request.js:1171:10)
    at emitOne (events.js:115:13)
    at Request.emit (events.js:210:7)
    at IncomingMessage.<anonymous> (/home/b/zenbot/node_modules/request/request.js:1091:12)
    at Object.onceWrapper (events.js:314:30)
    at emitNone (events.js:110:20)
    at IncomingMessage.emit (events.js:207:7)
    at endReadableNT (_stream_readable.js:1057:12)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)
```

The sell order already printed too and it said 'sold' for about 10 minutes before I got the error.

**Comment by ether-btc** [comment] 2017-10-27 13:55
I get some similiar error when trading ETH-BTC on bittrex too. It crashes the zenbot sometimes. When I restart zenbot after that, it doesn't lead to reproducable termination of the zenbot though. I can provide the error message and anything else that might be required (just let me know):

[bittrex crash.txt](https://github.com/carlos8f/zenbot/files/1422248/bittrex.crash.txt)

**Comment by brucetus** [comment] 2017-10-27 19:44
This a different error. My error crashes the bot and only happens after many hours of trading, while your's allows the bot to continue. Your's is the same as #280 I believe.

**Comment by luponata** [comment] 2017-11-09 19:41
got the same error today, already fixed the previous error with fix from #457

**Comment by brucetus** [comment] 2017-11-09 20:12
@lupotana If you read the first line of my issue you can see I used the fix from #457. You only get this error after doing the fix. Hence why this is named "DIFFERENT Bittrex error"

**Comment by luponata** [comment] 2017-11-10 09:15
@brucetus As i said, now i have the same error you are complaining in this "issue"

I also wrote that I also had the **previous error**, that i successfully resolved with the fix found on #457

**Comment by brucetus** [comment] 2017-11-10 16:31
@luponata My bad. Are you trading with BTC-USDT as well as other coin-BTC pairs? I have a feeling that might be what caused the problem.

**Comment by luponata** [comment] 2017-11-10 22:23
@brucetus i'm only using SNT-BTC, still testing!

**Comment by brucetus** [comment] 2017-11-10 23:48
Same here. If anybody has mod permissions can you please delete @ether-btc comment because it is addressed in a different issue and is taking up huge amounts of space.

**Comment by KryptoNova** [comment] 2017-11-15 02:04
I think I have solved the problem.  It appears that every once in a while the Bittrex API will choke and not return a result.  I'm not sure how this impacts checking for orders or 
I will do a pull request for this to see if everyone agrees with the modification.

if the result from Bittrex is undefined, then do not process any trades.  It isn't the best case since no new trades will be pulled in, but it will prevent the bot from crashing till the site is available again.

Since I cannot force Bittrex to fail, I have no way to legitimately test this.  
I will put in a pull request with my changes to see if everyone agrees with them.  This will be my first time doing this, so wish me luck on getting it right.

**Comment by KryptoNova** [comment] 2017-11-15 23:23
I got another one of these errors with the fix in place.  I was worried that since it wasn't able to be duplicated due to a problem at Bittrex, this would happen again.
I have come up with a Plan B and it should have been my Plan A.  
New pull request coming soon.

**Comment by KryptoNova** [comment] 2017-11-16 00:47
Just had a Bittrex hiccup.  The code change I just put into the newest pull request handles it and recovers without killing Zenbot.  After several retries, it began to read the API again.

Here is proof:
![image](https://user-images.githubusercontent.com/18106038/32867859-7fb8acde-ca3d-11e7-9934-53d7580e818d.png)

**Comment by brucetus** [comment] 2017-11-16 01:36
Thanks KryptoNova you're a hero.

**Closed as completed** 2017-11-16 13:30 UTC
Labels: bug
