### ISSUE TITLE
Bot throwing exception and  stopping in live trade and paper mode

### ISSUE THREAD

**Issue by code4passion** [DeviaVir/zenbot#787] opened 2017-12-03 10:27 UTC
I sometimes get following exception sometimes when trading in live/paper mode

```
events.js:183
      throw er; // Unhandled 'error' event
      ^

Error: Replaced by new connection
    at Connection.onStanza (/Users/dshetyo/hackspace/zenbot/node_modules/node-xmpp-core/lib/Connection.js:363:17)
    at StreamParser.<anonymous> (/Users/dshetyo/hackspace/zenbot/node_modules/node-xmpp-core/lib/Connection.js:231:10)
    at emitOne (events.js:116:13)
    at StreamParser.emit (events.js:211:7)
    at SaxLtx.<anonymous> (/Users/dshetyo/hackspace/zenbot/node_modules/@xmpp/streamparser/index.js:69:14)
    at emitOne (events.js:116:13)
    at SaxLtx.emit (events.js:211:7)
    at SaxLtx._handleTagOpening (/Users/dshetyo/hackspace/zenbot/node_modules/ltx/lib/parsers/ltx.js:38:12)
    at SaxLtx.write (/Users/dshetyo/hackspace/zenbot/node_modules/ltx/lib/parsers/ltx.js:127:18)
    at StreamParser.write (/Users/dshetyo/hackspace/zenbot/node_modules/@xmpp/streamparser/index.js:134:17)
    at Connection.onData (/Users/dshetyo/hackspace/zenbot/node_modules/node-xmpp-core/lib/Connection.js:310:17)
    at emitOne (events.js:121:20)
    at TLSSocket.emit (events.js:211:7)
    at addChunk (_stream_readable.js:263:12)
    at readableAddChunk (_stream_readable.js:250:11)
    at TLSSocket.Readable.push (_stream_readable.js:208:10)
    at TLSWrap.onread (net.js:594:20)
```

**Comment by DeviaVir** [comment] 2017-12-04 09:27
@code4passion are you using the xmpp notifier?

**Comment by dshetyo** [comment] 2017-12-04 23:39
Yes. Is this error coz of xmpp notifier? I will test it without this notifier and update the issue.

**Comment by dshetyo** [comment] 2017-12-05 20:14
I tried to run bot without xmpp notifier and it works fine. Looks like the problem is specific to xmpp notifier.

**Comment by DeviaVir** [comment] 2017-12-06 11:33
I think the problem was that xmpp could not connect to the server, is that an accurate assumption?

**Comment by DeviaVir** [comment] 2018-02-28 11:46
Dear issue reporter,

We have slightly changed our github issue policy and would now kindly request folks that have questions that they ask them in our zenbot subreddit.

You can find it here: https://reddit.com/r/zenbot

This issue will be closed, but if you disagree with your ticket being marked as a question feel free to leave a comment defending your case.

Thanks for contributing time and effort!

Greetings,
🤖

**Closed as completed by DeviaVir** 2018-02-28 11:46 UTC
Labels: bug, question
