### ISSUE TITLE
NPM install fails

### ISSUE THREAD

**Issue by Corstiaan84** [DeviaVir/zenbot#589] opened 2017-10-05 14:45 UTC
First off; very well written software. Thank you :-).

When running `npm install` I get this message:

````
npm WARN deprecated node-uuid@1.4.8: Use uuid module instead
npm ERR! git clone git@github.com:github:carlos8f/numbro Cloning into bare repository '/home/pi/.npm/_git-remotes/git-github-com-github-carlos8f-numbro-0d91dbd1'...
npm ERR! git clone git@github.com:github:carlos8f/numbro fatal: remote error:
npm ERR! git clone git@github.com:github:carlos8f/numbro    is not a valid repository name
npm ERR! git clone git@github.com:github:carlos8f/numbro   Email support@github.com for help
npm ERR! notarget No compatible version found: numbro@'github:carlos8f/numbro'
npm ERR! notarget Valid install targets:
npm ERR! notarget ["1.0.3","1.0.4","1.0.5","1.1.0","1.1.1","1.2.1","1.2.2","1.3.0","1.3.1","1.3.2","1.3.3","1.4.0","1.5.0","1.5.1","1.5.2","1.6.0","1.6.1","1.6.2","1.7.0","1.7.1","1.8.0","1.8.1","1.9.0","1.9.1","1.9.2","1.9.3","1.10.0","1.10.1","1.11.0"]
npm ERR! notarget
npm ERR! notarget This is most likely not a problem with npm itself.
npm ERR! notarget In most cases you or one of your dependencies are requesting
npm ERR! notarget a package version that doesn't exist.

npm ERR! System Linux 4.9.41-v7+
npm ERR! command "/usr/bin/nodejs" "/usr/bin/npm" "install"
npm ERR! cwd /home/pi/repos/zenbot
npm ERR! node -v v4.8.2
npm ERR! npm -v 1.4.21
npm ERR! code ETARGET
npm ERR! git clone git@github.com:github:mkmarek/forex.analytics Cloning into bare repository '/home/pi/.npm/_git-remotes/git-github-com-github-mkmarek-forex-analytics-6492775d'...
npm ERR! git clone git@github.com:github:mkmarek/forex.analytics fatal: remote error:
npm ERR! git clone git@github.com:github:mkmarek/forex.analytics    is not a valid repository name
npm ERR! git clone git@github.com:github:mkmarek/forex.analytics   Email support@github.com for help
npm ERR!
npm ERR! Additional logging details can be found in:
npm ERR!     /home/pi/repos/zenbot/npm-debug.log
npm ERR! not ok code 0
````

Ideas?

**Comment by DeviaVir** [comment] 2017-10-05 18:31
Did you follow the docs here?
https://github.com/carlos8f/zenbot/blob/master/docs/raspberrypi.md

**Comment by Corstiaan84** [comment] 2017-10-05 18:35
Completely missed that guide. Will try it. Thanks.

**Comment by DeviaVir** [comment] 2017-10-12 12:43
@Corstiaan84 did this resolve your problem?

**Comment by Corstiaan84** [comment] 2017-10-12 12:49
Havent tried it yet. I have setup a new vps to run zenbot. Pi is just not
up to the job if you want to do it right.

Op do 12 okt. 2017 om 14:43 schreef Chase <notifications@github.com>

**Comment by rehoehle** [comment] 2017-10-23 00:20
I had the same problem under Ubuntu. The problem is that both repositories aren't accesible under "git://" i used the real npm packages that was working for the first. 

in packages.json:

```
"forex.analytics": "^0.0.15",
"numbro": "^1.11.0",
```
I don't know if it's working without any problems but with that changes i could install all packages.

**Comment by DeviaVir** [comment] 2018-02-28 11:36
Dear issue reporter,

We have slightly changed our github issue policy and would now kindly request folks that have questions that they ask them in our zenbot subreddit.

You can find it here: https://reddit.com/r/zenbot

This issue will be closed, but if you disagree with your ticket being marked as a question feel free to leave a comment defending your case.

Thanks for contributing time and effort!

Greetings,
🤖

**Closed as completed by DeviaVir** 2018-02-28 11:36 UTC
Labels: question
