### ISSUE TITLE
GDAX sell signal send but no sell and loose benefit

### ISSUE THREAD

**Issue by Seigneurhol** [DeviaVir/zenbot#732] opened 2017-11-18 11:24 UTC
Hi,
I notice a strange thing. I trading using gdax. Sometimes I have a send signal, no sell is made on GDAX, but the benefit fall instantly...
Is it a bug or a misunderstood of the way the bot work ?
![capture d ecran 2017-11-18 a 11 45 18](https://user-images.githubusercontent.com/12207947/32979740-5ebbc262-cc5b-11e7-94f2-1f479fd3fd58.png)
![capture d ecran 2017-11-18 a 11 45 26](https://user-images.githubusercontent.com/12207947/32979741-60b0c8d8-cc5b-11e7-84f6-cfb9dc5be54d.png)
![capture d ecran 2017-11-18 a 11 45 33](https://user-images.githubusercontent.com/12207947/32979743-63242ef2-cc5b-11e7-97f6-448c034bb280.png)

**Comment by rountrey** [comment] 2017-11-21 21:28
Depends on the strategy you are using. Mine will hit the buy number but not buy until it starts to go up. This also means it can keep going down after hitting that buy number and not buy.

**Comment by benjamincburns** [comment] 2018-01-03 09:08
I see this issue as well. See my [comment](https://github.com/DeviaVir/zenbot/issues/868#issuecomment-354963455) over on #868 for more info as to the cause(s).

**Comment by Seigneurhol** [comment] 2018-01-03 09:36
I think that was because my balance was too small (under 0.01 BTC) and it can’t sell. 
Thanks :)

**Comment by DeviaVir** [comment] 2018-02-28 11:42
Closing this one in favor of #868

**Closed as completed by DeviaVir** 2018-02-28 11:42 UTC
Labels: question
